# Generated by Django 3.2.6 on 2021-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='enable_presence_url',
            field=models.BooleanField(default=False),
        ),
    ]
