# Generated by Django 3.2.6 on 2021-08-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpaymentconfirmation',
            name='payment_confirmation',
            field=models.ImageField(upload_to='C:\\Github\\SEMAC-Project-Katerine\\katerine\\static\\PaymentConfirmations'),
        ),
    ]
