# Generated by Django 3.2.6 on 2021-09-10 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemacUserPasswordCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=12)),
                ('user_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
