# Generated by Django 3.2.6 on 2021-08-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonaldata',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Nome Completo'),
        ),
    ]
