# Generated by Django 3.2.6 on 2021-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_course',
            field=models.BooleanField(default=False),
        ),
    ]
