# Generated by Django 3.2.6 on 2021-08-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_alter_userpersonaldata_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonaldata',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userunespdata',
            name='ra',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
