# Generated by Django 3.2.6 on 2021-08-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0005_alter_userpersonaldata_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonaldata',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
    ]
