# Generated by Django 3.2.6 on 2021-08-25 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0006_alter_userpersonaldata_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemacUserAuthenticationCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=12)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
