# Generated by Django 3.2.6 on 2021-08-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0007_semacuserauthenticationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='semacuser',
            name='is_email_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
